# Custom Copilot Agent: AI Tooling Refactor Expert
# Specialized agent for the ongoing AI package restructure (Issue #33, PR #34)

name: ai-refactor-agent
description: Expert in the AI tooling refactor - moving tools to connectors

expertise:
  - LangChain StructuredTool creation
  - MCP (Model Context Protocol) server implementation
  - CrewAI tool integration
  - Tool abstraction patterns
  - Import path migrations

context:
  always_include:
    - path: .github/copilot-instructions.md
      reason: Current architecture direction
    - path: memory-bank/activeContext.md
      reason: Active refactor status
  
  # Note: Issue/PR numbers verified as of Dec 2025 - check current status
  issues:
    - number: 33
      reason: Main refactor issue defining the pattern
    - number: 34
      reason: Active PR implementing the changes

current_state: |
  The ai/ package is currently ACTIVE and supported. The refactor discussed in
  Issue #33 and PR #34 proposes moving towards a decentralized model where tools
  live alongside each connector. This is a PLANNED direction, not yet complete.
  
  CURRENT (active, supported):
    vendor_connectors/ai/tools/           # LangChain tools for connectors
    vendor_connectors/ai/providers/       # Multi-provider LLM support
    vendor_connectors/ai/connector.py     # AIConnector unified interface
    vendor_connectors/ai/workflows/       # LangGraph workflow builders
    
  TARGET PATTERN (for new connectors):
    vendor_connectors/meshy/agent_tools/  # Tools live with connector
    vendor_connectors/<service>/tools.py  # Future pattern for other connectors
    vendor_connectors/<service>/mcp.py    # MCP server with connector
  
  NOTE: Do NOT delete the ai/ package - it is actively used. Instead, new tools
  should follow the decentralized pattern while ai/ remains for backwards compatibility.

guidelines:
  - "Tools live WITH their connector, not in a central ai/ package"
  - "Each connector provides 3 interfaces: Python API, LangChain tools, MCP server"
  - "No wrapper classes (AIConnector, BaseLLMProvider) - users use LangChain directly"
  - "LangChain StructuredTool is the standard - works with LangChain, CrewAI, LangGraph"
  - "Entry points in pyproject.toml: <service>-mcp = vendor_connectors.<service>.mcp:main"
  - "Remove ai/ package entirely once all connectors migrated"

migration_pattern:
  step1_create_tools_file: |
    # In vendor_connectors/<service>/tools.py
    from langchain_core.tools import StructuredTool
    from pydantic import BaseModel, Field
    
    class Text3DInput(BaseModel):
        prompt: str = Field(description="Text description of 3D model")
        style: str = Field(default="realistic", description="Art style")
    
    def _generate_3d(prompt: str, style: str = "realistic") -> dict:
        from vendor_connectors.meshy import text3d
        result = text3d.generate(prompt, art_style=style)
        return {"task_id": result.id, "status": result.status}
    
    def get_tools() -> list[StructuredTool]:
        return [
            StructuredTool(
                name="meshy_generate_3d",
                description="Generate 3D model from text",
                func=_generate_3d,
                args_schema=Text3DInput
            )
        ]
  
  step2_create_mcp_server: |
    # In vendor_connectors/<service>/mcp.py
    # Note: Actual MCP imports may vary - check mcp package documentation
    # This is a conceptual example showing the pattern
    
    def create_server():
        # Import and configure MCP server
        # Implementation depends on mcp package version
        from .tools import get_tools
        
        # Example: Create server instance
        # server = configure_mcp_server("service-mcp")
        # for tool in get_tools():
        #     server.register_tool(tool)
        return server
    
    def main():
        server = create_server()
        # Start MCP server
        # server.run()
    
    if __name__ == "__main__":
        main()
  
  step3_update_pyproject: |
    # Add to pyproject.toml [project.scripts]
    [project.scripts]
    meshy-mcp = "vendor_connectors.meshy.mcp:main"
    
  step4_update_imports: |
    # OLD
    from vendor_connectors.ai.tools.meshy_tools import get_meshy_tools
    
    # NEW
    from vendor_connectors.meshy.tools import get_tools
    
  step5_delete_old: |
    # After migration complete:
    rm -rf src/vendor_connectors/ai/

tasks:
  - name: migrate_connector_tools
    prompt: |
      Migrate a connector's tools from ai/ to the connector package:
      1. Create <connector>/tools.py with StructuredTools
      2. Create <connector>/mcp.py with MCP server
      3. Update entry point in pyproject.toml
      4. Create tests for tools
      5. Update imports in any examples/docs
      6. Verify old ai/tools/<connector>_tools.py can be deleted
      
  - name: verify_migration
    prompt: |
      After migrating a connector:
      1. Test tools work: from vendor_connectors.<service>.tools import get_tools
      2. Test MCP server: <service>-mcp (command line)
      3. Run existing tests: uv run pytest tests/test_<service>*.py
      4. Check no imports from vendor_connectors.ai remain
      5. Update documentation

  - name: audit_ai_package
    prompt: |
      Check what's left in ai/ package:
      1. List files in src/vendor_connectors/ai/
      2. Identify which connectors still have tools in ai/tools/
      3. Check for any shared code that's actually needed
      4. Create migration plan for remaining connectors

breaking_changes:
  - old: "from vendor_connectors.ai.tools.meshy_tools import get_meshy_tools"
    new: "from vendor_connectors.meshy.tools import get_tools"
    
  - old: "from vendor_connectors.ai import AIConnector"
    new: "Use LangChain directly: from langchain_anthropic import ChatAnthropic"
    
  - old: "vendor_connectors.ai.providers.anthropic.AnthropicProvider"
    new: "Use langchain-anthropic directly, no wrapper needed"

examples:
  - file: src/vendor_connectors/meshy/tools.py
    description: Complete migration example with 8 tools
  - file: src/vendor_connectors/meshy/mcp.py
    description: MCP server implementation
  - pr: 34
    description: Full refactor PR showing deletions and migrations

related_issues:
  - 33: "Main refactor issue"
  - 34: "Active refactor PR"
  - 18: "Meshy connector (uses new pattern)"
  - 19: "Meshy interface improvements"
